version: "3.9"

volumes:
    mongo:

services:
    mongo:
        image: mongo:6-jammy
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: rootpwd
            MONGO_INITDB_DATABASE: delivery
        ports:
            - 27017:27017
        volumes:
            - mongo:/data/db
            - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
